In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
import scipy
import string
import pickle
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder            
from sklearn.svm import LinearSVC             
from sklearn.naive_bayes import BernoulliNB
from sklearn.ensemble import RandomForestClassifier          
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

from astropy.table import Table, Column
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

In [2]:
import folium
import matplotlib.pyplot as plt
import seaborn as sns
import chardet

In [3]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder() 

In [4]:
with open('C:\\Users\zarnab shahid\Downloads\CMAPS_newData2.csv', 'rb') as f:
    result = chardet.detect(f.read())  # or readline if the file is large
    
tr_df=pd.read_csv(r"C:\\Users\zarnab shahid\Downloads\CMAPS_newData2.csv",encoding=result['encoding'])
print("------------------------------------------------------")
print("------------------------------------------------------")
tr_df.head()

------------------------------------------------------
------------------------------------------------------


Posting  Date  Month   Year       Days  Time  \
0  Allama Iqbal Town    26       1  2018     Friday  0:00   
1  Allama Iqbal Town    21       3  2018  Wednesday  0:00   
2  Allama Iqbal Town    30       3  2018     Friday  0:00   
3  Allama Iqbal Town    26       4  2018   Thursday  0:00   
4  Allama Iqbal Town     3       5  2018   Thursday  0:00   

                             Offences    Offence Categories Part of the Day  \
0      Outraging the Modesty of Women  Crime Against Person             1st   
1                         Other Crime                Others             1st   
2                         Other Crime                Others             1st   
3  punjab arms ordinance bill of 2015             Ordinance             1st   
4                         Other Crime                Others             1st   

   Latitudes  Longitudes             TGAT  
0    31.5124     74.2845  31.5124,74.2845  
1    31.5124     74.2845  31.5124,74.2845  
2    31.5124     74.2845  31.5124,74.2845  
3    31.5124     74.2845  31.5124,74.2845  
4    31.5124     74.2845  31.5124,74.2845

In [5]:
tr_df.columns=['posting', 'date', 'month', 'year', 'day', 'time', 'offences', 'crime_categories','partoftheday','latitude','longitude','location']

In [6]:
# Sort the rows of dataframe by column 
d_df1 = tr_df.sort_values(by ='day')
d_df1.head()

posting  date  month  year     day   time  \
0      Allama Iqbal Town    26      1  2018  Friday   0:00   
6745               Cantt     8      6  2018  Friday   8:00   
23393             Mozang    21      9  2018  Friday  17:50   
6742               Cantt    19      1  2018  Friday   8:00   
23404         Saman Abad    24      8  2018  Friday  17:50   

                             offences      crime_categories partoftheday  \
0      Outraging the Modesty of Women  Crime Against Person          1st   
6745                      Other Crime                Others          2nd   
23393                 kite flying act                Others          5th   
6742                      Other Crime                Others          2nd   
23404                 kite flying act                Others          5th   

       latitude  longitude         location  
0       31.5124    74.2845  31.5124,74.2845  
6745    31.5196    74.3889  31.5196,74.3889  
23393   31.5597    74.3138  31.5597,74.3138  
6742    31.5196    74.3889  31.5196,74.3889  
23404   31.5356    74.2985  31.5356,74.2985

In [7]:
obj_df = tr_df

In [8]:
obj_df["offences_code"] = label_encoder.fit_transform(obj_df[["offences"]])
obj_df[["offences", "offences_code"]].head(11)

C:\Users\zarnab shahid\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


offences  offences_code
0                     Outraging the Modesty of Women             32
1                                        Other Crime             29
2                                        Other Crime             29
3                 punjab arms ordinance bill of 2015             68
4                                        Other Crime             29
5   punjab information temporary residence ordinance             70
6                                               Rape             40
7                                        Other Crime             29
8                                      M/Cycle Theft             24
9                                        Other Crime             29
10                                       Other Crime             29

In [9]:
d_df1['day']= label_encoder.fit_transform(d_df1['day']) 
d_df1['day'].unique()

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [10]:
d_df1['offences']= label_encoder.fit_transform(d_df1['offences']) 
d_df1['offences'].unique()

array([32, 29, 57, 25, 27, 65, 55, 33,  5, 24, 68, 47, 23, 20, 51, 42, 13,
        3, 74, 31, 14, 17, 37, 71,  8, 70, 21,  2, 18, 40,  9, 26, 38, 28,
       12, 48, 52, 62, 54, 60,  1, 50, 45, 72, 16, 44,  4, 10, 46, 35, 36,
       53, 15, 22, 11, 43, 69, 63,  0, 58, 39, 34, 61,  7, 64, 76, 75, 56,
       49, 19,  6, 30, 59, 66, 67, 73, 41], dtype=int64)

In [11]:
d_df1['offences']= label_encoder.fit_transform(d_df1['offences']) 
d_df1['offences'].unique()
d_df1['time']= label_encoder.fit_transform(d_df1['time']) 
d_df1['time'].unique()
d_df1['partoftheday']= label_encoder.fit_transform(d_df1['partoftheday']) 
d_df1['partoftheday'].unique()
d_df1['posting']= label_encoder.fit_transform(d_df1['posting']) 
d_df1['posting'].unique()
d_df1['location']= label_encoder.fit_transform(d_df1['location']) 
d_df1['location'].unique()

array([ 9, 12, 22, 15, 26, 27,  8,  2,  6, 21, 24, 11, 16, 13, 14,  0, 10,
        1,  5, 20,  3, 23,  4, 25,  7, 17, 19, 18], dtype=int64)

In [12]:
d_df1.columns

Index(['posting', 'date', 'month', 'year', 'day', 'time', 'offences',
       'crime_categories', 'partoftheday', 'latitude', 'longitude',
       'location'],
      dtype='object')

In [13]:
X = d_df1.drop([ 'posting', 'date', 'month', 'year', 'day', 'time',
       'crime_categories', 'partoftheday', 'latitude', 'longitude',
       'location'] , axis=1)
X.head()

offences
0            32
6745         29
23393        57
6742         29
23404        57

In [14]:
y = d_df1.drop(['posting', 'date', 'month', 'year', 'crime_categories', 'time', 'offences','partoftheday','latitude','longitude','location'] , axis=1)
y.head()

day
0        0
6745     0
23393    0
6742     0
23404    0

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

In [17]:
#rfc training data set
scores_rfc = cross_val_score(RandomForestClassifier(n_estimators=40),X_train, y_train.values.ravel(), cv=5)
np.average(scores_rfc)

0.18261595028717534

In [15]:
#rfc with full dataset
scores_rfc = cross_val_score(RandomForestClassifier(n_estimators=40),X, y.values.ravel(), cv=5)
np.average(scores_rfc)

0.16538028550703174

In [16]:
#knn with full dataset
scores_knn = cross_val_score(KNeighborsClassifier(n_neighbors=40),X,y.values.ravel(),cv=5)
np.average(scores_knn)

0.15940433168570164

In [17]:
#knn with train dataset
scores_knn = cross_val_score(KNeighborsClassifier(n_neighbors=40),X_train,y_train.values.ravel(),cv=5)
np.average(scores_knn)

0.17447759883282626

In [18]:
#dectree with full dataset 
scores_dec=cross_val_score(DecisionTreeClassifier( random_state=40),X,y.values.ravel(),cv=5)
np.average(scores_dec)

0.16517228829934974

In [19]:
#dectree with train dataset 
scores_dec=cross_val_score(DecisionTreeClassifier( random_state=40),X_train,y_train.values.ravel(),cv=5)
np.average(scores_dec)

0.18662790610302468

In [40]:
#lgr full dataset
scores_lgr = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X, y.values.ravel(),cv=5)
np.average(scores_lgr)

0.16594788182136624

In [21]:
#lgr train dataset
scores_lgr = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, y_train.values.ravel(),cv=5)
np.average(scores_lgr)

0.16693325701978884

In [15]:
#Random Forest

rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train.values.ravel())
rf.score(X_test, y_test.values.ravel())

0.18831747919143876

In [16]:
#saving pickle file
# save the model to disk
filename = 'finalized_model_day.sav'
pickle.dump(rf, open(filename, 'wb'))

In [17]:
# some time later...
 
# load the model from disk
loaded_model = pickle.load(open('finalized_model_day.sav', 'rb'))
result = loaded_model.score(X_test, y_test)
print(result)

0.18831747919143876


#key 
#'Friday' = 0 
#'Monday' = 1 
#'saturday'= 2 '
#Sunday'=3 , 
#'Tuesday'=4 , 
#'Thursday'=5,
#'Wednesday'=6. 

In [18]:
#PREDICTING ON UNSEEN EXAMPLE
#Taking Inputs:


#posting = int(input("Please enter your GRE Score :"))
crime = int(input("Please enter crime :"))


user_data = pd.DataFrame({'crime':[crime]})
print(user_data)

user_model = scipy.sparse.csr_matrix(user_data.values)
predict = loaded_model.predict(user_model)

if (predict == 0):
    print("There is a", result*100 , "% chance of this crime occuring on \033[1m Friday ")
elif(predict == 1):
    print("There is a", result*100 , "% chance of this crime occuring on  \033[1m Monday")
elif(predict == 2):
     print("There is a", result*100 , "% chance of this crime occuring on  \033[1m Saturday ")     
elif(predict == 3):
    print("There is a", result*100 , "% chance of this crime occuring on  \033[1m Sunday ")
elif(predict == 4):
    print("There is a", result*100 , "% chance of this crime occuring on  \033[1m Tuesday ")
elif(predict == 5):
    print("There is a", result*100 , "% chance of this crime occuring on  \033[1m Thursday")
elif(predict == 6):
    print("There is a", result*100 , "% chance of this crime occuring on  \033[1m Wednesday")

Please enter crime :35
   crime
0     35
There is a 18.831747919143876 % chance of this crime occuring on  Friday 
