In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
import scipy
import string
import pickle
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder            
from sklearn.svm import LinearSVC             
from sklearn.naive_bayes import BernoulliNB
from sklearn.ensemble import RandomForestClassifier          
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

from astropy.table import Table, Column
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

In [2]:
import folium
import matplotlib.pyplot as plt
import seaborn as sns
import chardet

In [3]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder() 

In [28]:
with open('C:\\Users\zarnab shahid\Downloads\CMAPS_newData2.csv', 'rb') as f:
    result = chardet.detect(f.read())  # or readline if the file is large
    
tr_df=pd.read_csv(r"C:\\Users\zarnab shahid\Downloads\CMAPS_newData2.csv",encoding=result['encoding'])
print("------------------------------------------------------")
print("------------------------------------------------------")
tr_df.head()

------------------------------------------------------
------------------------------------------------------


Posting  Date  Month   Year       Days  Time  \
0  Allama Iqbal Town    26       1  2018     Friday  0:00   
1  Allama Iqbal Town    21       3  2018  Wednesday  0:00   
2  Allama Iqbal Town    30       3  2018     Friday  0:00   
3  Allama Iqbal Town    26       4  2018   Thursday  0:00   
4  Allama Iqbal Town     3       5  2018   Thursday  0:00   

                             Offences    Offence Categories Part of the Day  \
0      Outraging the Modesty of Women  Crime Against Person             1st   
1                         Other Crime                Others             1st   
2                         Other Crime                Others             1st   
3  punjab arms ordinance bill of 2015             Ordinance             1st   
4                         Other Crime                Others             1st   

   Latitudes  Longitudes             TGAT  
0    31.5124     74.2845  31.5124,74.2845  
1    31.5124     74.2845  31.5124,74.2845  
2    31.5124     74.2845  31.5124,74.2845  
3    31.5124     74.2845  31.5124,74.2845  
4    31.5124     74.2845  31.5124,74.2845

In [29]:
tr_df.columns=['posting', 'date', 'month', 'year', 'day', 'time', 'offences', 'crime_categories','partoftheday','latitude','longitude','location']

In [30]:
# Sort the rows of dataframe by column 
m_df1 = tr_df.sort_values(by ='month')
m_df1.head()

posting  date  month  year       day   time  \
0      Allama Iqbal Town    26      1  2018    Friday   0:00   
20879         Green Town    30      1  2018   Tuesday  16:10   
11374         Johar Town    29      1  2018    Monday  11:15   
20861              Cantt     7      1  2018    Sunday  16:10   
11375         Johar Town    25      1  2018  Thursday  11:15   

                             offences      crime_categories partoftheday  \
0      Outraging the Modesty of Women  Crime Against Person          1st   
20879                     Other Crime                Others          5th   
11374                Cheque Dishonour  Crime Against Person          3rd   
20861                       Narcotics                Others          5th   
11375                   Miscellaneous                Others          3rd   

       latitude  longitude         location  
0       31.5124    74.2845  31.5124,74.2845  
20879   31.4346    74.3074  31.4346,74.3074  
11374   31.4621    74.2942  31.4621,74.2942  
20861   31.5196    74.3889  31.5196,74.3889  
11375   31.4621    74.2942  31.4621,74.2942

In [7]:
obj_df = tr_df

In [8]:
obj_df["offences_code"] = label_encoder.fit_transform(obj_df[["offences"]])
obj_df[["offences", "offences_code"]].head(11)

C:\Users\zarnab shahid\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


offences  offences_code
0                     Outraging the Modesty of Women             32
1                                        Other Crime             29
2                                        Other Crime             29
3                 punjab arms ordinance bill of 2015             68
4                                        Other Crime             29
5   punjab information temporary residence ordinance             70
6                                               Rape             40
7                                        Other Crime             29
8                                      M/Cycle Theft             24
9                                        Other Crime             29
10                                       Other Crime             29

In [9]:
obj_df["offences_code"].unique()

array([32, 29, 68, 70, 40, 24,  5, 42, 20, 28,  9, 25, 57, 51, 47, 71, 33,
       31, 17, 72,  2, 27, 18, 55,  8, 14, 50, 48, 65, 13, 23,  3, 26, 37,
       62, 59, 43, 49, 38, 46, 12, 44,  4,  1, 74,  7, 56, 21, 11, 16, 10,
       36, 52, 15, 64, 19, 54, 60, 34, 39, 22, 69, 66, 53, 75, 58, 61, 63,
        0, 35, 67, 41,  6, 45, 76, 73, 30], dtype=int64)

In [10]:
obj_df["offences"].unique()

array(['Outraging the Modesty of Women', 'Other Crime',
       'punjab arms ordinance bill of 2015',
       'punjab information temporary residence ordinance', 'Rape',
       'M/Cycle Theft', 'Burglary', 'Robbery', 'Kidnapping',
       'Non-Fatal Accident', 'Cheque Dishonour', 'Miscellaneous',
       'kite flying act', 'begging act ', 'anti-norcotics act',
       'punjab security ordinance 2015', 'Overspeeding',
       'Other Vehicle Theft', 'Hurt (personal feud)',
       'punjab sound system regulation ordinance',
       'Attack on Govt. Servant', 'Narcotics', 'Illegal Extortion',
       'electricity act', 'Car Theft', 'Gambling', 'arms ordinance act',
       'anti-terrorism act', 'price control act', 'Fatal Accident',
       'M/Cycle Snatching', 'Attempted Murder', 'Murder',
       'Punjab Local Government ordinance 2016', 'one wheeling act',
       'loud speaker act', 'Secretarianism',
       'anti-terrorism act 1997 ata',
       'Punjab Marriage Function ordinance 2016', 'Tresspass

In [31]:
m_df1['month']= label_encoder.fit_transform(m_df1['month']) 
m_df1['month'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [32]:
m_df1['offences']= label_encoder.fit_transform(m_df1['offences']) 
m_df1['offences'].unique()

array([32, 29,  9, 27, 25, 60, 33, 51, 70, 14, 47, 15, 17, 55, 37, 65, 68,
       23, 20,  5, 24, 26, 21, 57, 48, 42,  8,  3,  2, 46, 40, 18, 62, 31,
       28, 74,  1, 71, 50, 72, 13,  0, 36, 16,  4,  7, 44, 64, 38, 39, 54,
       10, 58, 43, 61, 11, 22, 53, 52, 34, 12, 69, 75, 63, 19, 66, 76, 45,
       35, 30, 49,  6, 59, 56, 67, 73, 41], dtype=int64)

In [33]:
X = m_df1.drop([ 'posting', 'date', 'month', 'year', 'day', 'time',
       'crime_categories', 'partoftheday', 'latitude', 'longitude',
       'location'] , axis=1)
X.head()

offences
0            32
20879        29
11374         9
20861        27
11375        25

In [34]:
y = m_df1.drop(['posting', 'date', 'day', 'year', 'crime_categories', 'time', 'offences','partoftheday','latitude','longitude','location'] , axis=1)
y.head()

month
0          0
20879      0
11374      0
20861      0
11375      0

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

In [37]:
#rfc training data set
scores_rfc = cross_val_score(RandomForestClassifier(n_estimators=40),X_train, y_train.values.ravel(), cv=5)
np.average(scores_rfc)

0.13553078665387677

In [38]:
#rfc with full dataset
scores_rfc = cross_val_score(RandomForestClassifier(n_estimators=40),X, y.values.ravel(), cv=5)
np.average(scores_rfc)

0.12994023799492713

In [39]:
#knn with full dataset
scores_knn = cross_val_score(KNeighborsClassifier(n_neighbors=40),X,y.values.ravel(),cv=5)
np.average(scores_knn)

0.10767936382937957

In [40]:
#knn with train dataset
scores_knn = cross_val_score(KNeighborsClassifier(n_neighbors=40),X_train,y_train.values.ravel(),cv=5)
np.average(scores_knn)

0.12114639252968214

In [41]:
#dectree with full dataset 
scores_dec=cross_val_score(DecisionTreeClassifier( random_state=40),X,y.values.ravel(),cv=5)
np.average(scores_dec)

0.129702315432569

In [42]:
#dectree with train dataset 
scores_dec=cross_val_score(DecisionTreeClassifier( random_state=40),X_train,y_train.values.ravel(),cv=5)
np.average(scores_dec)

0.13623706527532264

In [43]:
#lgr full dataset
scores_lgr = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X, y.values.ravel(),cv=5)
np.average(scores_lgr)

0.11061640397438324

In [44]:
#lgr train dataset
scores_lgr = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, y_train.values.ravel(),cv=5)
np.average(scores_lgr)

0.11211869283960987

In [45]:
#Random Forest

rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train.values.ravel())
rf.score(X_test, y_test.values.ravel())

0.13837693222354341

In [46]:
#saving pickle file
# save the model to disk
filename = 'finalized_model_month.sav'
pickle.dump(rf, open(filename, 'wb'))

In [47]:
# some time later...
 
# load the model from disk
loaded_model = pickle.load(open('finalized_model_month.sav', 'rb'))
result = loaded_model.score(X_test, y_test)
print(result)

0.13837693222354341


In [17]:
#PREDICTING ON UNSEEN EXAMPLE
#Taking Inputs:


#posting = int(input("Please enter your GRE Score :"))
crime = int(input("Please enter crime :"))


user_data = pd.DataFrame({'crime':[crime]})


user_model = scipy.sparse.csr_matrix(user_data.values)
predict = loaded_model.predict(user_model)

if (predict == 0):
    print("There is a", result*100 , "% chance of this crime occuring in \033[1m  January" )
elif(predict == 1):
    print("There is a", result*100 , "% chance of this crime occuring in \033[1m Februaury")
elif(predict == 2):
     print("There is a", result*100 , "% chance of this crime occuring in \033[1m March")     
elif(predict == 3):
    print("There is a", result*100 , "% chance of this crime occuring in \033[1m April")
elif(predict == 4):
    print("There is a", result*100 , "% chance of this crime occuring in \033[1m May")
elif(predict == 5):
    print("There is a", result*100 , "% chance of this crime occuring in \033[1m June")
elif(predict == 6):
    print("There is a", result*100 , "% chance of this crime occuring in \033[1m July")
elif(predict == 7):
    print("There is a", result*100 , "% chance of this crime occuring in \033[1m August")
elif(predict == 8):
    print("There is a", result*100 , "% chance of this crime occuring in \033[1m September")
elif(predict == 9):
    print("There is a", result*100 , "% chance of this crime occuring in\033[1m October")
elif(predict == 10):
    print("There is a", result*100 , "% chance of this crime occuring in6 \033[1m November")
elif(predict == 11):
    print("There is a", result*100 , "% chance of this crime occuring in \033[1m December")

Please enter crime :34
There is a 14.164684898929844 % chance of this crime occuring in October
